# AI模型配置
ai:
  model:
    # API密钥，请替换为你的实际密钥
    api-key: sk-
    # API接口地址，DeepSeek API接口基础地址
    api-url: https://api.deepseek.com/v1/chat/completions
    # 默认模型名称
    model-name: deepseek-chat
    # 超时时间（毫秒）
    timeout: 60000
    # 是否启用代理
    proxy-enabled: false
    # 代理主机
    proxy-host: 127.0.0.1
    # 代理端口
    proxy-port: 7890
